### ISSUE TITLE
White screen bug with H5AD and HDF5 format

### ISSUE THREAD

**Issue by dunstone-a** [jkanche/kana#117]
Hi,

I have noticed a bug when adding input files through the *'10x HDF5 matrix'* or the *'H5AD'* option. If the **Add** button is pressed before selecting a file then the web page will go completely blank and requires a refresh. This also happens if there is already another `.h5ad` file loaded.

**Comment by jkanche** [comment]
@dunstone-a this PR: https://github.com/jkanche/kana/pull/118 should fix this bug. let me know if you continue to see this error
