### ISSUE TITLE
I don't think the custom selection indices are sorted

### ISSUE THREAD

**Issue by LTLA** [jkanche/kana#131]
![Screenshot from 2022-07-09 02-03-39](https://user-images.githubusercontent.com/8166669/178099322-a84c5d88-a455-4531-967e-a3125d8a534f.png)

From printing the `payload.selection` received by the worker on a `computeCustomMarkers` signal.

Safest to sort them on the **bakana** side, provided that this has no ill effects on the **kana** side.

**Comment by LTLA** [comment]
Latest `master` version of **bakana** will now throw if unsorted, duplicate or out-of-range indices are passed in.

**Comment by jkanche** [comment]
#133 fixes this
