### ISSUE TITLE
Multiple datasets not working

### ISSUE THREAD

**Issue by PeteHaitch** [jkanche/kana#136]
I tried loading 2 datasets, both in '10x HDF5 matrix' format (from CellRanger v7) and get the following error:

```
08:56:46: (downloadsdb) store initialized
08:56:46: (kanadb) store initialized
08:56:47: analysis state created
08:56:47: bakana initialized
08:58:24: preflight_input finished
08:58:26: preflight_input finished
08:58:31: preflight_input finished
08:59:11: preflight_input finished
08:59:19: preflight_input finished
08:59:26: --- Analyis started---
08:59:26: Error: cannot assign undefined parameter to 'inputs.sample_factor'
````

The same error occurs if I use the 'Matrix Market file' format of these datasets.
These two datasets both contain GEX and ADT assays.
Each dataset works fine when loaded and analysed individually.

Can I provide any other info that will help figure out what's going wrong?

**Comment by LTLA** [comment]
Oops. Looks like we didn't test the new `subset` UI for multi-uploads. bd9c30277b141755f41df4c6cefa370c51508c8d should hopefully fix it once it deploys.

**Comment by PeteHaitch** [comment]
Great, thanks. 
Can it handle datasets with different gene information?
I.e. For these samples, `DropletUtils::read10xCounts()` will complain that `gene information differs between runs` so they have to be read in individually and then combined.

**Comment by PeteHaitch** [comment]
Nevermind, tested it with the new version and it worked.
Thanks for the quick fix

**Comment by LTLA** [comment]
I think so, the Reader just ignores all but the ID and symbol fields anyway. It'll fail if the intersection is non-zero, though.

Does the fix work?
