### ISSUE TITLE
"ADT"/"adt" not recognised as alternative experiment in SingleCellExperiment objects

### ISSUE THREAD

**Issue by PeteHaitch** [jkanche/kana#146]
Thank you for supporting _SummarizedExperiment_ objects in `.rds` files, it's a great feature!

I was testing it out with some local data and found that if the alternative experiment was called 'ADT' or 'adt' then **kana** failed to recognise it but the documentation suggests this should work.

**Comment by LTLA** [comment]
Oops: https://github.com/LTLA/bakana/commit/759129d4fa3594d5a60ec2c94b9b07d64660021a

Hopefully that will propagate to NPM and @jkanche can just bump this build after he picks up his bike tomorrow.

**Comment by PeteHaitch** [comment]
Thanks, Aaron.

We tend to store ADTs and HTOs in separate alternative experiments.
Do you reckon it'd be possible to make it selectable or what's going to happen if there are multiple matches to that regex?

**Comment by LTLA** [comment]
Currently, I think "ADT*" will be selected first, then "HTO*", then "Antibody*".

Making it selectable is possible, but not exactly a one-liner. We'd need to rethink the opening UI to provide a place for this option. The preflights would also need to change given that the intersection needs to be recomputed on user input.

**Comment by jkanche** [comment]
Do either of you have a dataset I can test this on ? @PeteHaitch or @LTLA ?

**Comment by jkanche** [comment]
technically, the version should work; https://github.com/jkanche/kana/commit/e7d75658eaf58213294947738d13ba61029081fb

@PeteHaitch let us know if this doesn't work.

**Comment by PeteHaitch** [comment]
I'll test it out when I next get a chance and report back. Thanks!

**Comment by PeteHaitch** [comment]
Confirming that with an SCE containing multiple alternative experiments, namely:

```r
> altExps(sce)
List of length 2
names(2): HTO ADT
```

that now the `ADT` one gets picked up as that containing the antibody derived tags.
Thanks guys!
