### ISSUE TITLE
Pre-analyzed Seurat object

### ISSUE THREAD

**Issue by kokitsuyuzaki** [jkanche/kana#156]
Hi, @jkanche

I recently know this tool `kana` from @LTLA' s presentation at BioC Asia 2022.
Can `kana` also be used for pre-analyzed objects with coordinates of t-SNE/UMAP or cluster labels by clustering?
Also, does `kana` accept `Seurat` objects?
In my case, I want to use `kana` just for visualization of a `Seurat` object with skipping the analyzing steps.

Thanks in advance.

**Comment by LTLA** [comment]
We have this capability (to visualize pre-analyzed datasets) for our in-house deployment of **kana**. This part could be incorporated into the open-source version, depending on priorities.

Regardless, it seems unlikely that we will be supporting **Seurat** objects, for reasons discussed in LTLA/scRNAseq#15. If we were to provide this "visualization-only" mode, it would probably focus on SE objects in RDS files; probably also H5AD files, with the hope that the format remains stable.

**Comment by kokitsuyuzaki** [comment]
Yes, I know the community of `Seurat`, `Scanpy`, and `Bioconductor` are split.

> it would probably focus on SE objects in RDS files

There is no problem, I'll convert `Seurat` object to `SingleCellExperiment` object in some way like `as.SingleCellExperiment` function.

I'm looking forward to the new feature of kana.

Thanks,
