### ISSUE TITLE
During initialization of app: INIT ERROR; ReferenceError: SharedArrayBuffer is not defined

### ISSUE THREAD

**Issue by aghr** [jkanche/kana#161]
Following the link `https://www.jkanche.com/kana/` even before the app seems to have initialized and before trying to load input data I see this error:

"INIT ERROR | ReferenceError: SharedArrayBuffer is not defined |  If the error is related to input data, we support [Matrix Market], [10X v3 HDF5] or H5AD formats.  |  If not, please report the issue on [GitHub](https://github.com/jkanche/kana/issues)."

I work with Firefox 110.0 (64-bit) on Ubuntu 20.04.5 LTS 64-bit.

**Comment by jkanche** [comment]
I cannot reproduce the issue. Do you have any extensions that might be blocking JS or service workers? If you notice any errors in devtools, that might also help me debug the issue. 

also works on chromium on linux. 

PS. I'm on Firefox 108.0.1 on Manjaro.

![image](https://user-images.githubusercontent.com/399324/220139214-968214b1-3b99-4cba-9b8a-b95c30c51701.png)

**Comment by jkanche** [comment]
hope it works! please reopen if it does not work for you
