### ISSUE TITLE
Throw in some code for the new saving and reloading 

### ISSUE THREAD

**Issue by LTLA** [jkanche/kana#162]
Speaking of saving, we'll need two options to "save configuration" and "save results". The former will save the analysis config for fast reload, while the latter will save the results to a ZIP file.

# Saving analysis results

I'll talk about saving analysis results first. This should be as easy as:

```js
let files = bakana.saveSingleCellExperiment(superstate, "results", { forceBuffer: true });
let zipbuffer = bakana.zipFiles(files); // transfer this to main thread for download prompt.
```

# Saving configuration to file

For saving the configuration, this is the true "replacement" for the `saveAnalysis` machinery. I believe it should be something like the following for a file export:

```js
let buffers = [];
let saver = (name, format, file) => {
    let id = String(buffers.length);
    buffers.push(file.buffer());
    return id;
};

// Returns a configuration object.
let collected = await bakana.serializeConfiguration(superstate, saver);

// Let's zip it all up!
const zipper = new JSZip();
zipper.file("config.json", JSON.stringify(collected));
for (var i = 0; i < buffers.length; i++) {
    zipper.file("datasets/" + String(i), buffers[i]);
}
let zipbuffer = await zipper.generateAsync({ type: "uint8array" }); // transfer to main thread for download.
```

Reloading should also be fairly straightforward.

```js
const unzipped = await JSZip.loadAsync(zipbuffer);
let config = JSON.parse(await unzipped.file("config.json").async("string"));

let buffers = {};
for (const x of unzipped.files) {
     if (x.startsWith("datasets/")) {
         let current = await buffers.file(x).async("uint8array");
         buffers[x.split("/")[1]] = current;
     }
}

// This re-runs the entire analysis, so throw startFun/finishFun callbacks here.
let restate = await bakana.unserializeConfiguration(superstate, id => buffers[id]);
```

# Saving configuration to IndexedDB

Similar deal as above, the only difference is the definition of `saver`.

```js
let collected = [];
let saver =  (name, format, file) => { // basically linkKanaDb with an extra arg.
    let buffer = file.buffer();
    var md5 = await hashwasm.md5(buffer);
    var id = type + "_" + file.name() + "_" + buffer.length + "_" + md5;
    var ok = await kana_db.saveFile(id, buffer);
    if (!ok) {
      throw "failed to save file '" + id + "' to KanaDB";
    }
    collected.push(id);
    return id;
};

let collected = await bakana.serializeConfiguration(superstate, saver);
const enc = new TextEncoder;
let config = enc.encode(JSON.stringify(collected));
let id = await kana_db.saveAnalysis(null, config, collected, title);
```

And reloading:

```js
let restate = await bakana.unserializeConfiguration(superstate, kana_db.loadFile);
```

The only tricky part is that we might need to slap a magic string to the end of the title to distinguish the JSON configuration saves from the old-style `*.kana` saves. This provides back-compatibility for people still loading kana files in the browser.

**Comment by jkanche** [comment]
trying to save as SCE fails 

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/399324/224554945-f267ac74-3606-4988-a534-386aeae62200.png">

**Comment by jkanche** [comment]
reference - https://github.com/jkanche/kana/commit/ab15610c6984ef3efaec875433644ff37483d740

**Comment by jkanche** [comment]
also load from indexedDB throws serializations errors

**Comment by LTLA** [comment]
First issue: try adding the patch in kanaverse/bakana#64 to `node_modules/bakana/browser/dump/abstract/dump.js`.

Second issue: what's the traceback?

**Comment by jkanche** [comment]
cool, the patch works

**Comment by LTLA** [comment]
Patch is in 2.0.5
