### ISSUE TITLE
deployment links incorrect

### ISSUE THREAD

**Issue by colindaven** [jkanche/kana#74]
Hi, 

both links on the github page lead to a 404, but the link on twitter is correct/works.

cheers

**Comment by jkanche** [comment]
interesting, does this link work ? 

https://www.jkanche.com/kana/ ?

**Comment by jkanche** [comment]
Thanks @colindaven for reporting, I renamed the repo recently and forgot to update the links, [this commit](https://github.com/jkanche/kana/commit/2e1b7e63c60b77600ee5030e6c12e75b402c5367) should fix this

**Comment by colindaven** [comment]
Yes, that link works
