### ISSUE TITLE
Could you provide a sample dataset?

### ISSUE THREAD

**Issue by slowkow** [jkanche/kana#77]
Could I please ask if you could provide a data file that is known to work with this app?

I tried `GSE117963_10X_whole_aorta_filtered_gene_bc_matrices_h5.h5` from this URL: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE117963

The app seems to be doing nothing. In the side bar on the right, this is what I see:

```
Generating nearest neighbor graph to compute clusters....
```

After 10 minutes, the same message is still displayed and the app is still doing nothing.

When I click the wrench icon ("What's happening?"), this is what I see:

![image](https://user-images.githubusercontent.com/209714/149012035-fdbd7ff4-bde6-4e0e-bcac-850bfdded900.png)

**Comment by LTLA** [comment]
If you're supplying a 10X HDF5 file, you'll need a file produced by Cellranger v3 or higher, i.e., something with a `matrix` group rather than groups named after the reference genome. (See [here](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/h5_matrices) for details.) In your case, your file has a `mm10` group, which silently causes an error - we're still working on properly showing exceptions.

**Comment by slowkow** [comment]
This file seems to work:

GSM5584161_Nkcells_sample7-17.filtered_feature_bc_matrix.h5

available from:

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5584161

**Comment by LTLA** [comment]
Oops. I was looking in the wrong place for those symbols. Refresh the app (maybe need to clear the cache) and they should show up now.

**Comment by slowkow** [comment]
> Refresh the app (maybe need to clear the cache) and they should show up now.

Usually I press <kbd>Cmd</kbd><kbd>Shift</kbd><kbd>R</kbd> in Google Chrome to refresh the cache, but I'm not sure if it worked this time because I still don't see gene names for the GSM5584161 file.

When I open the "wrench" icon to see the log, here is what I see:

```
19:30:1 - KanaDB_store - Success
19:30:1 - INIT - Success: ScranJS/WASM initialized
19:30:12 - inputs_DATA - Success: Count matrix loaded
19:30:12 - quality_control_metrics_DATA - Success: QC metrics computed
19:30:12 - quality_control_thresholds_DATA - Success: QC thresholds computed
19:30:12 - quality_control_filtered_DATA - Success: QC filtering completed
19:30:12 - normalization_DATA - Success: Log-normalization completed
19:30:12 - feature_selection_DATA - Success: Variance modelling completed
19:30:12 - pca_DATA - Success: Principal components analysis completed
19:30:13 - neighbor_index_DATA - Success: Neighbor search index constructed
19:30:13 - snn_find_neighbors_DATA - Success: Shared nearest neighbor search completed
19:30:13 - snn_build_graph_DATA - Success: Shared nearest neighbor graph constructed
19:30:14 - snn_cluster_graph_DATA - Success: Community detection from SNN graph complete
19:30:15 - choose_clustering_DATA - Success: Clustering of interest chosen
19:30:15 - marker_detection_DATA - Success: Marker detection complete
19:30:15 - custom_marker_management_DATA - Success: Pruning of custom markers finished
19:30:15 - setMarkersForCluster - Success: GET_MARKER_GENE done
19:30:20 - tsne_DATA - Success: t-SNE completed
19:30:25 - umap_DATA - Success: UMAP completed
```

Is it possible to print a line at the beginning with information about which version of code is running?
