### ISSUE TITLE
Integration of multiple datasets

### ISSUE THREAD

**Issue by MichaelSchulzGSH** [jkanche/kana#88]
Dear all, 
1. thanks to the authors for this great web page, I am really beginner in coding and scData analysis.
2. Would there be any option to extend the applicability of this tool to integrate several datasets, preserving however the origin of every single one?
3. Thanks a lot and best wishes, Michael

**Comment by LTLA** [comment]
> * Would there be any option to extend the applicability of this tool to integrate several datasets, preserving however the origin of every single one?

Yes, this is in the plan somewhere (see https://github.com/LTLA/CppMnnCorrect for the method that we plan to use). But it'll have to wait until we squeeze out the manuscript.

**Comment by jkanche** [comment]
@MichaelSchulzGSH we now support integration of multiple datasets using the MNN correction algorithm.
