### ISSUE TITLE
Aesthetic fiddling

### ISSUE THREAD

**Issue by LTLA** [jkanche/kana#92]
- [x] Switch analysis modal to a left-side panel that uses the entire height of the page. #93 
- [x] Highlight the header that leads to the currently selected popover. #93

**Comment by jkanche** [comment]
- [ ] fix aspect ratio of plots in Gallery (especially for tsne/umap)
- [ ] panel layout for gallery (download, restore and delete)
   - [ ] restore state from gallery tsne/umap plots
- [ ] restyle log section
- [ ] fix flickering screen when the pong game is enabled
- [ ]

**Comment by LTLA** [comment]
- [ ] Cluster numbers are wack
- [ ] we should have a better way of identifying clusters from the plot. maybe highlight the cluster and show its name on mouse-over

**Comment by jkanche** [comment]
some of these are irrelevant after the new set of changes happening in #158
